PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE android_metadata (locale TEXT);
INSERT INTO android_metadata VALUES('en_GB');
CREATE TABLE `expense` (`id_expense` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `amount` INTEGER NOT NULL, `category` TEXT, `title` TEXT, `note` TEXT, `date` TEXT, `location` TEXT);
INSERT INTO expense VALUES(2,50000,'Rent','Sewa pajero','-','2024-12-19',NULL);
INSERT INTO expense VALUES(3,50000,'Dining Out','Salero Bundo',replace('iga bakar\n','\n',char(10)),'2024-12-24',NULL);
INSERT INTO expense VALUES(4,600000,'Groceries','Kipas angin','-','2024-12-26',NULL);
INSERT INTO expense VALUES(5,250000,'Utilities','Listrik','-','2024-12-29',NULL);
INSERT INTO expense VALUES(6,2000000,'Utilities','Listrik','-','2024-12-30',NULL);
INSERT INTO expense VALUES(7,2000000,'Utilities','Listrik','-','2024-12-27',NULL);
INSERT INTO expense VALUES(8,2500000,'Rent',replace('added\n','\n',char(10)),'-','2024-12-27',NULL);
INSERT INTO expense VALUES(9,2000000,'Utilities','Listrik','-','2024-12-30',NULL);
CREATE TABLE `income` (`id_income` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `amount` INTEGER NOT NULL, `category` TEXT, `title` TEXT, `note` TEXT, `date` TEXT, `location` TEXT);
INSERT INTO income VALUES(2,800000,'Salary','Gaji ','-','2024-12-17',NULL);
INSERT INTO income VALUES(3,1000000,'Freelance Work','Desain pos ronda','-','2024-12-23',NULL);
INSERT INTO income VALUES(4,900000,'Investments','Invest saham','-','2024-12-25',NULL);
INSERT INTO income VALUES(5,5000000,'Salary','Gaji, bulanan','-','2024-12-27',NULL);
INSERT INTO income VALUES(6,50000000,'Salary','Gaji bulanan','-','2024-12-27',NULL);
INSERT INTO income VALUES(7,50000,'Business Profit','coba','ya','2024-12-28',NULL);
INSERT INTO income VALUES(8,50000,'Business Profit','bisa','ga','2024-12-28',NULL);
CREATE TABLE `wallet` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `jumlah_balance` INTEGER NOT NULL);
CREATE TABLE `budgeting` (`id_budget` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `budget_name` TEXT, `target_amount` INTEGER NOT NULL, `saved_amount` INTEGER NOT NULL, `target_date` TEXT, `category` TEXT, `note` TEXT);
INSERT INTO budgeting VALUES(1,'beli kuma',200000,500000,'2024-12-31','kuma','');
CREATE TABLE `budgetTransaction` (`id_budget_transaction` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `id_budget` INTEGER NOT NULL, `amount` INTEGER NOT NULL, `transaction_date` TEXT, `note` TEXT, FOREIGN KEY(`id_budget`) REFERENCES `budgeting`(`id_budget`) ON UPDATE NO ACTION ON DELETE CASCADE );
CREATE TABLE `templateInput` (`id_template` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `type` TEXT, `amount` INTEGER NOT NULL, `category` TEXT, `title` TEXT, `note` TEXT, `reminder` INTEGER NOT NULL, `date` TEXT);
INSERT INTO templateInput VALUES(6,'Income',50000000,'Salary','Gaji bulanan','-',10,'2024-12-27');
INSERT INTO templateInput VALUES(7,'Expense',2000000,'Utilities','Listrik','-',30,'2024-12-30');
CREATE TABLE room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT);
INSERT INTO room_master_table VALUES(42,'55477d7ad0d1657bce3e3bd3b363dd8c');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('templateInput',7);
INSERT INTO sqlite_sequence VALUES('income',8);
INSERT INTO sqlite_sequence VALUES('expense',9);
INSERT INTO sqlite_sequence VALUES('budgeting',1);
CREATE INDEX `index_budgetTransaction_id_budget` ON `budgetTransaction` (`id_budget`);
COMMIT;